// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messagepb/message.proto

package messagepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LongRequest struct {
	ClientString         string   `protobuf:"bytes,1,opt,name=ClientString,proto3" json:"ClientString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongRequest) Reset()         { *m = LongRequest{} }
func (m *LongRequest) String() string { return proto.CompactTextString(m) }
func (*LongRequest) ProtoMessage()    {}
func (*LongRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d4f3249a385fa58, []int{0}
}

func (m *LongRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongRequest.Unmarshal(m, b)
}
func (m *LongRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongRequest.Marshal(b, m, deterministic)
}
func (m *LongRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongRequest.Merge(m, src)
}
func (m *LongRequest) XXX_Size() int {
	return xxx_messageInfo_LongRequest.Size(m)
}
func (m *LongRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LongRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LongRequest proto.InternalMessageInfo

func (m *LongRequest) GetClientString() string {
	if m != nil {
		return m.ClientString
	}
	return ""
}

type LongResponse struct {
	ServerString         string   `protobuf:"bytes,1,opt,name=ServerString,proto3" json:"ServerString,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LongResponse) Reset()         { *m = LongResponse{} }
func (m *LongResponse) String() string { return proto.CompactTextString(m) }
func (*LongResponse) ProtoMessage()    {}
func (*LongResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1d4f3249a385fa58, []int{1}
}

func (m *LongResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LongResponse.Unmarshal(m, b)
}
func (m *LongResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LongResponse.Marshal(b, m, deterministic)
}
func (m *LongResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LongResponse.Merge(m, src)
}
func (m *LongResponse) XXX_Size() int {
	return xxx_messageInfo_LongResponse.Size(m)
}
func (m *LongResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LongResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LongResponse proto.InternalMessageInfo

func (m *LongResponse) GetServerString() string {
	if m != nil {
		return m.ServerString
	}
	return ""
}

func init() {
	proto.RegisterType((*LongRequest)(nil), "Message.LongRequest")
	proto.RegisterType((*LongResponse)(nil), "Message.LongResponse")
}

func init() { proto.RegisterFile("messagepb/message.proto", fileDescriptor_1d4f3249a385fa58) }

var fileDescriptor_1d4f3249a385fa58 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x2d, 0x48, 0xd2, 0x87, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8,
	0x7d, 0x21, 0x5c, 0x25, 0x43, 0x2e, 0x6e, 0x9f, 0xfc, 0xbc, 0xf4, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4,
	0xe2, 0x12, 0x21, 0x25, 0x2e, 0x1e, 0xe7, 0x9c, 0xcc, 0xd4, 0xbc, 0x92, 0xe0, 0x92, 0xa2, 0xcc,
	0xbc, 0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x14, 0x31, 0x25, 0x23, 0x2e, 0x1e, 0x88,
	0x96, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x90, 0x9e, 0xe0, 0xd4, 0xa2, 0xb2, 0xd4, 0x22, 0x54,
	0x3d, 0xc8, 0x62, 0x46, 0xbe, 0x5c, 0x3c, 0xce, 0xf9, 0x79, 0x65, 0xa9, 0x45, 0xc5, 0x89, 0x25,
	0x99, 0xf9, 0x79, 0x42, 0xb6, 0x5c, 0x1c, 0xc1, 0x05, 0xa9, 0x89, 0xd9, 0x99, 0x79, 0xe9, 0x42,
	0x22, 0x7a, 0x50, 0xc7, 0xe8, 0x21, 0xb9, 0x44, 0x4a, 0x14, 0x4d, 0x14, 0x62, 0x99, 0x12, 0x83,
	0x06, 0xa3, 0x01, 0xa3, 0x13, 0x77, 0x14, 0x27, 0xdc, 0x67, 0x49, 0x6c, 0x60, 0x2f, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0xa7, 0x8d, 0x30, 0xed, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConversationClient is the client API for Conversation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConversationClient interface {
	Speaking(ctx context.Context, opts ...grpc.CallOption) (Conversation_SpeakingClient, error)
}

type conversationClient struct {
	cc *grpc.ClientConn
}

func NewConversationClient(cc *grpc.ClientConn) ConversationClient {
	return &conversationClient{cc}
}

func (c *conversationClient) Speaking(ctx context.Context, opts ...grpc.CallOption) (Conversation_SpeakingClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Conversation_serviceDesc.Streams[0], "/Message.Conversation/Speaking", opts...)
	if err != nil {
		return nil, err
	}
	x := &conversationSpeakingClient{stream}
	return x, nil
}

type Conversation_SpeakingClient interface {
	Send(*LongRequest) error
	Recv() (*LongResponse, error)
	grpc.ClientStream
}

type conversationSpeakingClient struct {
	grpc.ClientStream
}

func (x *conversationSpeakingClient) Send(m *LongRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *conversationSpeakingClient) Recv() (*LongResponse, error) {
	m := new(LongResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConversationServer is the server API for Conversation service.
type ConversationServer interface {
	Speaking(Conversation_SpeakingServer) error
}

// UnimplementedConversationServer can be embedded to have forward compatible implementations.
type UnimplementedConversationServer struct {
}

func (*UnimplementedConversationServer) Speaking(srv Conversation_SpeakingServer) error {
	return status.Errorf(codes.Unimplemented, "method Speaking not implemented")
}

func RegisterConversationServer(s *grpc.Server, srv ConversationServer) {
	s.RegisterService(&_Conversation_serviceDesc, srv)
}

func _Conversation_Speaking_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConversationServer).Speaking(&conversationSpeakingServer{stream})
}

type Conversation_SpeakingServer interface {
	Send(*LongResponse) error
	Recv() (*LongRequest, error)
	grpc.ServerStream
}

type conversationSpeakingServer struct {
	grpc.ServerStream
}

func (x *conversationSpeakingServer) Send(m *LongResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *conversationSpeakingServer) Recv() (*LongRequest, error) {
	m := new(LongRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Conversation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Message.Conversation",
	HandlerType: (*ConversationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Speaking",
			Handler:       _Conversation_Speaking_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "messagepb/message.proto",
}
